### ISSUE TITLE
Support of user auth is missing 

### ISSUE THREAD

**Issue by mkeyran** [asvetlov/bloggertool#1]
The "user" parameter cannot be passed to the blog application.

```
> blog user
usage: blog [-h] [-v] [-V] [--show-traceback] [--usage]
            [--console-encoding CONSOLE_ENCODING]
            {add,diff,html,info,init,label,link,ls,open,publish,push,rinfo,rls,rm,ropen,show,help}
            ...
blog: error: invalid choice: 'user' (choose from 'add', 'diff', 'html', 'info', 'init', 'label', 'link', 'ls', 'open', 'publish', 'push', 'rinfo', 'rls', 'rm', 'ropen', 'show', 'help')
```

**Comment by asvetlov** [comment]
You don't need to register user anymore.
bloggertool will ask you to login if needed.

**Comment by mkeyran** [comment]
Nope, it ain't.

```
[keyran:/tmp/2]$ blog init .      
INFO Create project /tmp/2
[keyran:/tmp/2]$ touch article.md
[keyran:/tmp/2]$ blog add article.md
ERROR Cannot find secret file '/tmp/2/.client_secret.json' beside to config file '/tmp/2/.blogspot.yaml'
```

or should I provide the secret file by myself?

**Comment by asvetlov** [comment]
Oops. I'll take a look.
Sorry, bloggertool has the only user for now, I've created it for myself and use to make posts to asvetlov.blogspot.com only.
google dropped support for old auth schema and I switched to new one with removing some old code.

Aha, I've found the issue.

You should go to https://console.developers.google.com first and ask for "Blogger API v3" access. Manager will grant required rights. If you don't override quotas it's free, I don't pay for my blog.

After that you need to open "Credentials" page in https://console.developers.google.com, press "Download Json" button and save the file as `.client_secret.json` in the root of your blog project (the directory used for `blog init` call).

That's it.

Sorry, I see no way to automatize blog registration procedure by Google API calls but maybe should add those instructions to README.

**Comment by mkeyran** [comment]
Thanks!
Your tool provides much more functionality for blogger than anything i've found for now, so thanks for work.

**Comment by asvetlov** [comment]
Sure!
